### ISSUE TITLE
Pythonista 1.6 beta: AttributeError: 'MyScene' object has no attribute 'player'

### ISSUE THREAD

**Issue by Tkizzy** [ywangd/pythonista-tools-installer#2]
This error comes up when running CloudJump2.py installed via ptinstaller

**Comment by Tkizzy** [comment]
CloudJump 1:

Attribute Error: 'Rect' object has no attribute 'top'

**Comment by ywangd** [comment]
I am sorry but you'll have to raise the issues with the authors who actually wrote these two games. The Installer just install the scripts (download and save from the web). If a script is erroneous, there is nothing the Installer can do.

For your reference, the original sources of above games are as follows:
CloudJump: https://gist.github.com/BashedCrab/9098744
CloudJump2: https://github.com/tjferry14/Cloud-Jump-2
