### ISSUE TITLE
SyntaxError: invalid syntax (pyintaller.py, line 347)

### ISSUE THREAD

**Issue by wireddude** [ywangd/pythonista-tools-installer#3]
when I try to run the script on the latest version of pythonista, it gives me the following error:

```
SyntaxError: invalid syntax (pyintaller.py, line 347)
```

it's in the line with the following code:

```
self.github_installer.get_github_user_re
```

any ideas what I might be doing wrong?

Thanks,
David

**Comment by ywangd** [comment]
It does not look like the complete line of code. The complete [Line 347](https://github.com/ywangd/pythonista-tools-installer/blob/master/ptinstaller.py#L347) is as follows:

``` python
            elif self.github_installer.get_github_user_repo(btn.tool_url):
```

Did you just download the file? Maybe the file is not completely downloaded?

**Comment by wireddude** [comment]
Yes! that was the problem. I guess the file got cutoff during download and I didn't realize it. I'm in business now, thanks!
- David
