### ISSUE TITLE
Question : best way to update ?

### ISSUE THREAD

**Issue by wireddude** [ywangd/pythonista-tools-installer#4]
Is the best way to update a previously installed app to just delete then reinstall?

**Comment by ywangd** [comment]
That is correct.

To implement an update function, it requires to check remote version and
track local version. This can be done but even with that in place, an
update is still going to be uninstall + install internally (just automated).

On Thursday, 21 January 2016, David Kanter notifications@github.com wrote:

> Is the best way to update a previously installed app to just delete then
> reinstall?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ywangd/pythonista-tools-installer/issues/4.

## 

---

```
                  Life is elsewhere
```

**Comment by wireddude** [comment]
Thanks
